# Rendering
markdown: redcarpet
redcarpet:
  extensions: ["strikethrough"]
highlighter: pygments

# Permalinks
permalink: pretty

# Setup
title: Kar Epker
url: karepker.github.io

author:
  name: 'Kar Epker'
  url: karepker.github.io
