# Permalinks
permalink: /:title/

excerpt_separator: <!--more-->

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from

# Setup
title: Kar Epker
url: https://karepker.com
enforce_ssl: karepker.com
description: Oh Spongebob, whyyyyyy?

author:
  name: 'Kar Epker'
  url: https://karepker.com

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

kramdown:
  input: GFM
  hard_wrap: false

sass:
  style: compressed

defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
