# Dependencies
markdown: redcarpet
redcarpet:
  extensions: ["strikethrough"]
highlighter: pygments

# Permalinks
permalink: pretty

# Setup
title: Kar Epker
tagline: 'etc ...'
description: 'Where I share some of my writing.'
url: karepker.github.io

author:
  name: 'Kar Epker'
  url: karepker.github.io
