# Permalinks
permalink: /:title/

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from

# Setup
title: Kar Epker
url: https://karepker.com
enforce_ssl: karepker.com
description: Oh Spongebob, whyyyyyy?

author:
  name: 'Kar Epker'
  url: https://karepker.com

exclude: [Gemfile]

kramdown:
  input: GFM
  hard_wrap: false
