# Dependencies
markdown: kramdown
highlighter: pygments

# Permalinks
permalink: pretty

# Setup
title: Kar Epker
tagline: 'etc ...'
description: 'Where I share some of my writing.'
url: karepker.github.io

author:
  name: 'Kar Epker'
  url: karepker.github.io

# Custom vars
version: 2.0.0

github:
  repo: https://karepker.github.com

gems:
  - jekyll-feed
